# Generated by Django 4.2 on 2023-06-02 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('identifier', models.CharField(max_length=14, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('nomeSocial', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField()),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('failed_login_attempts_count', models.IntegerField(default=0)),
                ('blocked_at', models.DateTimeField(null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencia', models.IntegerField()),
                ('numero', models.IntegerField()),
                ('chavePix', models.CharField(max_length=100, unique=True)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('limite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativa', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('juros', models.DecimalField(decimal_places=2, default=0.05, max_digits=10)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('valorPagar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('aprovado', models.BooleanField(default=False)),
                ('observação', models.CharField(blank=True, max_length=100, null=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm.conta')),
            ],
        ),
        migrations.CreateModel(
            name='Parcelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vezes', models.IntegerField(default=1)),
                ('valorParcela', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dataPagamento', models.DateField()),
                ('valorPago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('emprestimo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adm.emprestimo')),
            ],
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remetenteNome', models.CharField(max_length=100)),
                ('destinatarioNome', models.CharField(max_length=100)),
                ('chavePix', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('p', 'Pix'), ('t', 'Transferencia'), ('d', 'Cartao')], max_length=1)),
                ('valor', models.DecimalField(decimal_places=2, default='p', max_digits=10)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.CharField(max_length=50)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatario', to='adm.conta')),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remetente', to='adm.conta')),
            ],
        ),
        migrations.CreateModel(
            name='Investimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prazo', models.DateTimeField(auto_now_add=True)),
                ('saldoInvestido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('local', models.CharField(max_length=50)),
                ('finalizado', models.BooleanField(default=False)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm.conta')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('uf', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=15, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('observacao', models.CharField(blank=True, max_length=100, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cartoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('d', 'Debito'), ('c', 'Credito'), ('b', 'Crebito')], default='b', max_length=1)),
                ('numero', models.CharField(default='', max_length=20, unique=True)),
                ('bandeira', models.CharField(default='G', max_length=1)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm.conta')),
            ],
        ),
    ]
