# Generated by Django 4.2 on 2023-06-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0002_cliente_inscricao_estadual_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprestimo',
            old_name='observação',
            new_name='observacao',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rg',
            field=models.CharField(max_length=9, null=True, unique=True),
        ),
    ]
